package vmessconfig

import (
	"fmt"
	"github.com/v2fly/v2ray-core/v4/infra/conf"
	"github.com/yindaheng98/vmessconfig/util"
	"os"
)

type BaseConfig struct {
	PingConfig *PingConfig `json:"pingConfig"`
}

type SingleNodeConfig struct {
	BaseConfig
	OutboundInsertBeforeTag string `json:"outboundInsertBeforeTag"`
}

func DefaultSingleNodeConfig() *SingleNodeConfig {
	return &SingleNodeConfig{
		BaseConfig:              BaseConfig{PingConfig: DefaultPingConfig()},
		OutboundInsertBeforeTag: "vmessconfig-outbound-insert",
	}
}

type BalancerConfig struct {
	BaseConfig
	OutboundInsertBeforeTag string `json:"outboundInsertBeforeTag"`
	TagFormat               string `json:"tagFormat"`
	BalancerInsertToTag     string `json:"balancerInsertToTag"`
	MaxSelect               uint   `json:"maxSelect"`
}

func DefaultBalancerConfig() *BalancerConfig {
	return &BalancerConfig{
		BaseConfig:              BaseConfig{PingConfig: DefaultPingConfig()},
		OutboundInsertBeforeTag: "vmessconfig-outbound-insert",
		TagFormat:               "vmessconfig-autogenerated-%d",
		BalancerInsertToTag:     "vmessconfig-autogenerated-balancer",
		MaxSelect:               8,
	}
}

func getSortedVmessList(urls []string, config *PingConfig, stopCh <-chan os.Signal) ([]string, error) {
	vmesslists := make([]string, 0)
	for _, url := range urls {
		vmesslist, err := util.GetVmessList(url)
		if err != nil {
			continue
		}
		vmesslists = append(vmesslists, vmesslist...)
	}
	vmessstats := VmessPingAll(vmesslists, config, stopCh)
	vmesslists = util.VmessSort(vmessstats)
	return vmesslists, nil
}

func VmessConfigBalancer(urls []string, template *conf.Config, config *BalancerConfig, stopCh <-chan os.Signal) (*conf.Config, error) {
	vmesslist, err := getSortedVmessList(urls, config.PingConfig, stopCh)
	if err != nil {
		return nil, err
	}
	max := int(config.MaxSelect)
	if len(vmesslist) < max {
		max = len(vmesslist)
	}
	outboundDetourConfigs := util.VmessListParse(vmesslist[0:max], config.PingConfig.UseMux, config.PingConfig.AllowInsecure)
	template = util.VmessBalancerConfigMerge(outboundDetourConfigs, template, config.TagFormat, config.OutboundInsertBeforeTag, config.BalancerInsertToTag)
	return template, nil
}

func VmessConfigSingleNode(urls []string, template *conf.Config, config *SingleNodeConfig, stopCh <-chan os.Signal) (*conf.Config, error) {
	vmesslist, err := getSortedVmessList(urls, config.PingConfig, stopCh)
	if err != nil {
		return nil, err
	}
	outboundDetourConfig, err := util.VmessParse(vmesslist[0], config.PingConfig.UseMux, config.PingConfig.AllowInsecure)
	if err != nil {
		return nil, err
	}
	template = util.VmessSingleNodeConfigMerge(outboundDetourConfig, template, config.OutboundInsertBeforeTag)
	return template, nil
}

func VmessConfig(urls []string, template *conf.Config, config interface{}, stopCh <-chan os.Signal) (*conf.Config, error) {
	var c interface{} = config
	switch inst := c.(type) {
	case *BalancerConfig:
		return VmessConfigBalancer(urls, template, inst, stopCh)
	case *SingleNodeConfig:
		return VmessConfigSingleNode(urls, template, inst, stopCh)
	default:
		return nil, fmt.Errorf("INVALID CONFIG TYPE: %+v", inst)
	}
}
