package vmessconfig

import (
	"github.com/v2fly/v2ray-core/v4/infra/conf"
	"github.com/yindaheng98/vmessconfig/util"
	"os"
)

type SingleNodeConfig struct {
	PingConfig              *PingConfig `json:"pingConfig"`
	TagFormat               string      `json:"tagFormat"`
	OutboundInsertBeforeTag string      `json:"outboundInsertBeforeTag"`
}

func DefaultSingleNodeConfig() *SingleNodeConfig {
	return &SingleNodeConfig{
		PingConfig:              DefaultPingConfig(),
		TagFormat:               "vmessconfig-autogenerated-%d",
		OutboundInsertBeforeTag: "vmessconfig-outbound-insert",
	}
}

type BalancerConfig struct {
	SingleNodeConfig
	BalancerInsertToTag string `json:"balancerInsertToTag"`
	MaxSelect           int    `json:"maxSelect"`
}

func DefaultBalancerConfig() *BalancerConfig {
	return &BalancerConfig{
		SingleNodeConfig:    *DefaultSingleNodeConfig(),
		BalancerInsertToTag: "vmessconfig-autogenerated-balancer",
		MaxSelect:           8,
	}
}

func getSortedVmessList(url string, config *PingConfig, stopCh <-chan os.Signal) ([]string, error) {
	vmesslist, err := util.GetVmessList(url)
	if err != nil {
		return nil, err
	}
	vmessstats := VmessPingAll(vmesslist, config, stopCh)
	vmesslist = util.VmessSort(vmessstats)
	return vmesslist, nil
}

func VmessConfigBalancer(url string, template *conf.Config, config *BalancerConfig, stopCh <-chan os.Signal) (*conf.Config, error) {
	vmesslist, err := getSortedVmessList(url, config.PingConfig, stopCh)
	if err != nil {
		return nil, err
	}
	max := config.MaxSelect
	if len(vmesslist) < max {
		max = len(vmesslist)
	}
	outboundDetourConfigs := util.VmessListParse(vmesslist[0:max], config.PingConfig.UseMux, config.PingConfig.AllowInsecure)
	template = util.VmessBalancerConfigMerge(outboundDetourConfigs, template, config.TagFormat, config.OutboundInsertBeforeTag, config.BalancerInsertToTag)
	return template, nil
}

func VmessConfigSingleNode(url string, template *conf.Config, config *SingleNodeConfig, stopCh <-chan os.Signal) (*conf.Config, error) {
	vmesslist, err := getSortedVmessList(url, config.PingConfig, stopCh)
	if err != nil {
		return nil, err
	}
	outboundDetourConfig, err := util.VmessParse(vmesslist[0], config.PingConfig.UseMux, config.PingConfig.AllowInsecure)
	if err != nil {
		return nil, err
	}
	template = util.VmessSingleNodeConfigMerge(outboundDetourConfig, template, config.OutboundInsertBeforeTag)
	return template, nil
}
